name: Build to dockerhub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}

      # 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/firefoxvnc:latest
