name: 自动部署 SAP

on:
  workflow_dispatch:  # 只允许手动触发
    inputs:
      environment:
        description: '选择部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - staging
          - production
      region:
        description: '选择部署区域'
        required: true
        default: 'SG'
        type: choice
        options:
          - SG  # 新加坡
          - US  # 美国
      app_name:
        description: '应用名称（可选，留空则自动生成）'
        required: false
        default: ''

env:
  DOCKER_IMAGE: ghcr.io/mytcgd/firefoxvnc:latest
  MEMORY: 2048M
  DISK: 2048M

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CF CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf8-cli

    - name: Determine CF API endpoint and app name
      run: |
        # 设置API端点
        if [ "${{ github.event.inputs.region }}" = "SG" ]; then
          echo "CF_API=https://api.cf.ap21.hana.ondemand.com" >> $GITHUB_ENV
          RANDOM_STR=$(head /dev/urandom | tr -dc 'a-z' | head -c 6)
          DEFAULT_APP_NAME="sg$RANDOM_STR"
        elif [ "${{ github.event.inputs.region }}" = "US" ]; then
          echo "CF_API=https://api.cf.us10-001.hana.ondemand.com" >> $GITHUB_ENV
          RANDOM_STR=$(head /dev/urandom | tr -dc 'a-z' | head -c 6)
          DEFAULT_APP_NAME="us$RANDOM_STR"
        fi
        
        # 设置应用名称（如果用户提供了则使用，否则使用默认）
        if [ -n "${{ github.event.inputs.app_name }}" ]; then
          echo "APP_NAME=${{ github.event.inputs.app_name }}" >> $GITHUB_ENV
        else
          echo "APP_NAME=$DEFAULT_APP_NAME" >> $GITHUB_ENV
        fi
        
        echo "使用API端点: $CF_API"
        echo "应用名称: $APP_NAME"

    - name: Login to Cloud Foundry
      run: |
        if [ "${{ github.event.inputs.region }}" = "SG" ]; then
          cf login -a ${{ env.CF_API }} -u "${{ secrets.EMAIL }}" -p "${{ secrets.PASSWORD }}" -o "${{ secrets.SG_ORG }}" -s "${{ secrets.SPACE }}"
        elif [ "${{ github.event.inputs.region }}" = "US" ]; then
          cf login -a ${{ env.CF_API }} -u "${{ secrets.EMAIL }}" -p "${{ secrets.PASSWORD }}" -o "${{ secrets.US_ORG }}" -s "${{ secrets.SPACE }}"
        fi

    - name: Deploy application
      run: |
        cf push ${{ env.APP_NAME }} --docker-image ${{ env.DOCKER_IMAGE }} -m ${{ env.MEMORY }} -k ${{ env.DISK }} --health-check-type port

    - name: Set environment variables
      run: |
        # VNC密码、分辨率及github备份、nezha相关
        cf set-env ${{ env.APP_NAME }} AUTO_BACKUP "${{ secrets.AUTO_BACKUP }}"
        cf set-env ${{ env.APP_NAME }} AUTO_RESTORE "${{ secrets.AUTO_RESTORE }}"
        cf set-env ${{ env.APP_NAME }} INTERVALINSECONDS "${{ secrets.INTERVALINSECONDS }}"
        cf set-env ${{ env.APP_NAME }} VNC_PASSWORD "${{ secrets.VNC_PASSWORD }}"
        cf set-env ${{ env.APP_NAME }} RESOLUTION "${{ secrets.RESOLUTION }}"
        cf set-env ${{ env.APP_NAME }} GBACKUP_USER "${{ secrets.GBACKUP_USER }}"
        cf set-env ${{ env.APP_NAME }} GBACKUP_REPO "${{ secrets.GBACKUP_REPO }}"
        cf set-env ${{ env.APP_NAME }} GBACKUP_TOKEN "${{ secrets.GBACKUP_TOKEN }}"
        cf set-env ${{ env.APP_NAME }} UUID "${{ secrets.UUID }}"
        cf set-env ${{ env.APP_NAME }} NEZHA_VERSION "${{ secrets.NEZHA_VERSION }}"
        cf set-env ${{ env.APP_NAME }} NEZHA_SERVER "${{ secrets.NEZHA_SERVER }}"
        cf set-env ${{ env.APP_NAME }} NEZHA_KEY "${{ secrets.NEZHA_KEY }}"
        cf set-env ${{ env.APP_NAME }} NEZHA_PORT "${{ secrets.NEZHA_PORT }}"
        
        # 可选：从文件读取环境变量(如果存在)
        if [ -f .env ]; then
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^# ]] && [[ -n "$line" ]]; then
              IFS='=' read -r key value <<< "$line"
              cf set-env ${{ env.APP_NAME }} "$key" "$value"
            fi
          done < .env
        fi

    - name: Restage application
      run: |
        cf restage ${{ env.APP_NAME }}

    - name: Verify deployment
      run: |
        cf app ${{ env.APP_NAME }}
        echo "Deployment completed successfully!"
